// examples/headless-nuxt/pages/[...path].vue
<script setup lang="ts">
const route = useRoute();
const api = useAmCmsClient();
const path = computed(() => `/${[route.params.path].flat().filter(Boolean).join('/')}`.replace(/\/+/g, '/'));

const { data, error } = await useAsyncData(`amcms-route-${path.value}`, () => api.getRoute(path.value), { watch: [path] });

useHead(() => ({
  title: titleOf(data.value, 'DEC CMS'),
  meta: [{ name: 'description', content: descriptionOf(data.value) }],
  link: dataOf<any>(data.value)?.route?.canonical ? [{ rel: 'canonical', href: dataOf<any>(data.value)?.route?.canonical }] : [],
}));

const apiError = computed(() => (error.value ? normalizeApiError(error.value) : null));
const content = computed(() => dataOf<any>(data.value)?.content ?? dataOf<any>(data.value));
const routeJson = computed(() => JSON.stringify(dataOf(data.value), null, 2));
</script>

<template>
  <main>
    <template v-if="apiError">
      <h1>Erreur API</h1>
      <div class="error">
        <strong>{{ apiError.status || 'Erreur' }}</strong>
        <span v-if="apiError.code"> · {{ apiError.code }}</span>
        <p>{{ apiError.message }}</p>
        <small v-if="apiError.requestId">Request ID : {{ apiError.requestId }}</small>
      </div>
    </template>

    <template v-else>
      <h1>{{ content?.title || path }}</h1>
      <p v-if="content?.excerpt">{{ content.excerpt }}</p>
      <pre>{{ routeJson }}</pre>
    </template>
  </main>
</template>

// examples/headless-next/app/[...path]/page.tsx
import type { Metadata } from 'next';
import { getRoute, normalizeApiError } from '../../lib/amcms';
import { dataOf, descriptionOf, titleOf } from '../../lib/payload';

type Props = { params: Promise<{ path?: string[] }> };

function pathFromParams(path?: string[]) {
  return `/${(path ?? []).join('/')}`.replace(/\/+/g, '/');
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const resolved = await params;
  const path = pathFromParams(resolved.path);
  try {
    const route = await getRoute(path);
    return {
      title: titleOf(route, 'DEC CMS'),
      description: descriptionOf(route),
      alternates: { canonical: (dataOf<any>(route)?.route?.canonical ?? dataOf<any>(route)?.canonical_url) as string | undefined },
    };
  } catch {
    return { title: 'Contenu indisponible' };
  }
}

export default async function DynamicPage({ params }: Props) {
  const resolved = await params;
  const path = pathFromParams(resolved.path);

  try {
    const route = await getRoute(path);
    const data = dataOf<any>(route);
    const content = data?.content ?? data;
    return (
      <main>
        <h1>{content?.title ?? data?.title ?? path}</h1>
        {content?.excerpt ? <p>{content.excerpt}</p> : null}
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
    );
  } catch (error) {
    const apiError = normalizeApiError(error);
    return (
      <main>
        <h1>Erreur API</h1>
        <div className="error">
          <strong>{apiError.status ?? 'Erreur'}</strong> {apiError.code ? `· ${apiError.code}` : ''}
          <p>{apiError.message}</p>
          {apiError.requestId ? <small>Request ID : {apiError.requestId}</small> : null}
        </div>
      </main>
    );
  }
}
